import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

import CookieBanner from "../components/CookiesBanner.jsx";
const useBlack = true;

export default function Home() {
    const [showBanner, setShowBanner] = useState("false 123");
    console.log("showBanner, showBanner", showBanner);
    if (showBanner || !useBlack)
        return (
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <h1 className={styles.title}>Любой контент</h1>
                    <h1 className={styles.title}>Адиль Алтаев</h1>

                    <p className={styles.description}>
                        Get started by editing{" "}
                        <code className={styles.code}>pages/index.js</code>
                    </p>
                    {/* <CookieBanner setShowBanner={setShowBanner} /> */}
                    {showBanner ? (
                        <CookieBanner setShowBanner={setShowBanner} />
                    ) : null}
                </main>

                <footer className={styles.footer}>
                    <a
                        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        Powered by{" "}
                        <span className={styles.logo}>
                            <Image
                                src="/vercel.svg"
                                alt="Vercel Logo"
                                width={72}
                                height={16}
                            />
                        </span>
                    </a>
                </footer>
            </div>
        );
    else {
        return (
            <div
                style={{
                    backgroundColor: "black",
                    color: "white",
                    height: "100vh",
                    padding: 50,
                }}
            >
                <h1>BLACK CONTENT</h1>
            </div>
        );
    }
}
